import type { MetadataRoute } from 'next';

// manifest.ts compiles to a route handler, and next.config.ts's `output: 'export'`
// refuses to prerender a route handler that has not declared itself static. The
// line looks like boilerplate next to a function returning a constant, which is
// the reason to say why it is here rather than delete it.
export const dynamic = 'force-static';

// Next does not prefix `start_url`, `scope`, or icon `src` values with `basePath`
// the way it does the <link> tags it generates from file conventions (icon.svg,
// apple-icon.png, favicon.ico). Under next.config.ts's `basePath: '/fieldtone'`
// and `output: 'export'`, this file prerenders to out/manifest.webmanifest, so
// every path below carries the prefix explicitly or the installed app ships
// pointed at the wrong scope.

// background_color and theme_color are zinc-950's sRGB value, matching
// globals.css's `--background: var(--color-zinc-950)`. Tailwind v4 defines that
// token in oklch, which a manifest can't consume, so the hex is pinned here by
// hand — if globals.css ever repoints --background, update this to match.
const ZINC_950 = '#09090b';

// The three PNGs below are derived from src/app/icon.svg and nothing in the
// build re-renders them, so they have to be regenerated by hand whenever the
// mark changes. Render them through Chromium, not ImageMagick: `magick` reaches
// SVG through an rsvg-convert delegate this repo does not depend on, and
// without it falls back to its own renderer, which mishandles the clipPath the
// mark is built from and writes a wrong PNG without failing.
//
//   node -e "
//     const { chromium } = require('@playwright/test');
//     const fs = require('fs');
//     (async () => {
//       const browser = await chromium.launch();
//       const svg = fs.readFileSync('src/app/icon.svg', 'utf8');
//       for (const [out, size] of [['public/icons/icon-192.png', 192], ['public/icons/icon-512.png', 512], ['src/app/apple-icon.png', 180]]) {
//         const page = await browser.newPage({ viewport: { width: size, height: size } });
//         await page.setContent('<style>html,body{margin:0}svg{display:block;width:' + size + 'px;height:' + size + 'px}</style>' + svg);
//         await page.screenshot({ path: out, omitBackground: true });
//       }
//       await browser.close();
//     })()
//   "
//
// icon-512-maskable.png is a copy of icon-512.png. The mark's furthest point
// sits 194 from centre on the 512 canvas, well inside the 204.8 safe radius a
// maskable icon can be cropped to, so a separately padded render would shrink
// the mark for nothing.
//
// src/app/favicon.ico comes off the same SVG: render 16, 32 and 48 the same
// way, then combine them with `magick <16> <32> <48> src/app/favicon.ico`.
export default function manifest(): MetadataRoute.Manifest {
	return {
		name: 'FieldTone',
		short_name: 'FieldTone',
		description: 'FieldTone turns the sound around you into generative ambient music.',
		display: 'standalone',
		start_url: '/fieldtone/',
		scope: '/fieldtone/',
		background_color: ZINC_950,
		theme_color: ZINC_950,
		icons: [
			{
				src: '/fieldtone/icons/icon-192.png',
				sizes: '192x192',
				type: 'image/png',
			},
			{
				src: '/fieldtone/icons/icon-512.png',
				sizes: '512x512',
				type: 'image/png',
			},
			{
				src: '/fieldtone/icons/icon-512-maskable.png',
				sizes: '512x512',
				type: 'image/png',
				purpose: 'maskable',
			},
		],
	};
}
